# Python Data Analysis Tasks

In [1]:
import pandas as pd
pd.__version__

'1.1.3'

### Task 1 - Data Ingestion

In [2]:
raw_df = pd.read_excel("Data.xlsx", header = 1, parse_dates = ['Response Date'])
raw_df
# Load excel file and set the header index to 1 (header is in row with index position 1 in excel file). 
# 1000 x 19 which is what we wanted.

,Response id,Response Date,Department,Manager,Gender-1,Gender-2,Company Grade,Universal Exports does a good job of keeping me informed about important news and events,I get a sense of achievement from the work I do in my job,Universal Exports has created an environment that encourages me to perform to the best of my abilities,I am proud to work for Universal Exports,I trust and respect the management of Universal Exports,I believe that Universal Exports really cares about my health and wellbeing,"All in all, Universal Exports is effectively managed and well-run",I believe that Universal Exports has fair and transparent processes for promoting people into new roles,I have access to opportunities to develop my career in Universal Exports,My manager treats me fairly,NPDSK,deqt43t
0,4,2020-07-13,IT,No,NaN,Female,A,5,4,4,5,4,3,4,4,2,4,NaN,NaN
1,21,2020-07-13,Marketing,No,NaN,Male,C,4,4,3,4,4,5,3,3,4,5,NaN,NaN
2,22,2020-07-13,Finance,No,NaN,Female,A,5,4,4,4,4,3,3,2,4,4,NaN,NaN
3,25,2020-07-13,Finance,No,NaN,Male,B,3,5,4,4,4,4,4,3,3,5,NaN,NaN
4,54,2020-07-13,Legal,No,NaN,Male,B,4,4,4,4,3,4,4,3,4,4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,899,2020-07-24,Legal,Yes,Female,NaN,D,4,4,3,4,4,4,4,3,3,4,NaN,NaN
996,901,2020-07-24,Marketing,Yes,Female,NaN,D,1,1,1,1,1,1,1,1,1,1,NaN,NaN
997,908,2020-07-24,Finance,Yes,Female,NaN,D,3,5,4,5,3,4,4,3,1,4,NaN,NaN
998,910,2020-07-24,IT,Yes,Male,NaN,D,4,4,4,5,4,4,4,4,4,3,NaN,NaN
999,969,2020-07-24,Legal,Yes,Female,NaN,D,4,4,3,3,3,4,2,2,3,3,NaN,NaN

In [3]:
df = raw_df.copy()

In [4]:
# General overview info about our dataset

# df.isna().sum()
# df.describe()
df.dtypes

Response id                                                                                                         int64
Response Date                                                                                              datetime64[ns]
Department                                                                                                         object
Manager                                                                                                            object
Gender-1                                                                                                           object
Gender-2                                                                                                           object
Company Grade                                                                                                      object
Universal Exports does a good job of keeping me informed about important news and events                            int64
I get a sense of achievement from the work I do in my job                                                           int64
Universal Exports has created an environment that encourages me to perform to the best of my abilities              int64
I am proud to work for Universal Exports                                                                            int64
I trust and respect the management of Universal Exports                                                             int64
I believe that Universal Exports really cares about my health and wellbeing                                         int64
All in all, Universal Exports is effectively managed and well-run                                                   int64
I believe that Universal Exports has fair and transparent processes for promoting people into new roles             int64
I have access to opportunities to develop my career in Universal Exports                                            int64
My manager treats me fairly                                                                                         int64
NPDSK                                                                                                             float64
deqt43t                                                                                                           float64
dtype: object

### Task 2 - Data Transformation

**Rename the "Company Grade" column as "Grade"**

In [5]:
df.rename({"Company Grade": "Grade"}, axis = "columns", inplace = True)
df.head()

,Response id,Response Date,Department,Manager,Gender-1,Gender-2,Grade,Universal Exports does a good job of keeping me informed about important news and events,I get a sense of achievement from the work I do in my job,Universal Exports has created an environment that encourages me to perform to the best of my abilities,I am proud to work for Universal Exports,I trust and respect the management of Universal Exports,I believe that Universal Exports really cares about my health and wellbeing,"All in all, Universal Exports is effectively managed and well-run",I believe that Universal Exports has fair and transparent processes for promoting people into new roles,I have access to opportunities to develop my career in Universal Exports,My manager treats me fairly,NPDSK,deqt43t
0,4,2020-07-13,IT,No,NaN,Female,A,5,4,4,5,4,3,4,4,2,4,NaN,NaN
1,21,2020-07-13,Marketing,No,NaN,Male,C,4,4,3,4,4,5,3,3,4,5,NaN,NaN
2,22,2020-07-13,Finance,No,NaN,Female,A,5,4,4,4,4,3,3,2,4,4,NaN,NaN
3,25,2020-07-13,Finance,No,NaN,Male,B,3,5,4,4,4,4,4,3,3,5,NaN,NaN
4,54,2020-07-13,Legal,No,NaN,Male,B,4,4,4,4,3,4,4,3,4,4,NaN,NaN

**Merge columns "Gender 1" and "Gender 2"**

In [6]:
# Fill null values in "Gender-1" with values in "Gender-2" for the corresponding row.
df = df.assign(**{'Gender-1': df['Gender-1'].fillna(df['Gender-2'])})

In [7]:
# Drop columns "Gender-2"
df.drop(columns = ['Gender-2'], inplace = True)

In [8]:
# Rename column "Gender-1"  to "Gender". 
df.rename({"Gender-1": "Gender"}, axis = 1, inplace = True)
gender_nulls = df['Gender'].isnull().sum()

print(f"There are {gender_nulls} null values in the Gender column. Gender-1 and Gender-2 merged succesfully.")

There are 0 null values in the Gender column. Gender-1 and Gender-2 merged succesfully.

In [9]:
# Check all values in "Gender" column are in consistent format
df['Gender'].unique()

array(['Female', 'Male', 'Female '], dtype=object)

In [10]:
# Remove space before and after the value
df['Gender'] = df['Gender'].str.strip()
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

**Remove columns 'NPDSK' and 'deqt43t'**

In [11]:
df.drop(columns = ['NPDSK', 'deqt43t'], inplace = True)
df.columns

Index(['Response id', 'Response Date', 'Department', 'Manager', 'Gender',
       'Grade',
       'Universal Exports does a good job of keeping me informed about important news and events',
       'I get a sense of achievement from the work I do in my job ',
       'Universal Exports has created an environment that encourages me to perform to the best of my abilities',
       'I am proud to work for Universal Exports',
       'I trust and respect the management of Universal Exports',
       'I believe that Universal Exports really cares about my health and wellbeing ',
       'All in all, Universal Exports is effectively managed and well-run',
       'I believe that Universal Exports has fair and transparent processes for promoting people into new roles',
       'I have access to opportunities to develop my career in Universal Exports',
       'My manager treats me fairly'],
      dtype='object')

**Add a conditional column**

Conditional column shows whether respondents' responses to *Universal Exports does a good job of keeping me informed about important news and events* was positive, neutral or negative.

In [12]:
swap_rating = {1: 'Negative', 
              2: 'Negative', 
              3: 'Neutral', 
              4: 'Positive', 
              5: 'Positive'}
    
df['Conditional Column'] = df['Universal Exports does a good job of keeping me informed about important news and events']
df['Conditional Column'] = df['Conditional Column'].map(swap_rating)

df.head()

,Response id,Response Date,Department,Manager,Gender,Grade,Universal Exports does a good job of keeping me informed about important news and events,I get a sense of achievement from the work I do in my job,Universal Exports has created an environment that encourages me to perform to the best of my abilities,I am proud to work for Universal Exports,I trust and respect the management of Universal Exports,I believe that Universal Exports really cares about my health and wellbeing,"All in all, Universal Exports is effectively managed and well-run",I believe that Universal Exports has fair and transparent processes for promoting people into new roles,I have access to opportunities to develop my career in Universal Exports,My manager treats me fairly,Conditional Column
0,4,2020-07-13,IT,No,Female,A,5,4,4,5,4,3,4,4,2,4,Positive
1,21,2020-07-13,Marketing,No,Male,C,4,4,3,4,4,5,3,3,4,5,Positive
2,22,2020-07-13,Finance,No,Female,A,5,4,4,4,4,3,3,2,4,4,Positive
3,25,2020-07-13,Finance,No,Male,B,3,5,4,4,4,4,4,3,3,5,Neutral
4,54,2020-07-13,Legal,No,Male,B,4,4,4,4,3,4,4,3,4,4,Positive

**Add a custom column**

The custom column shows both 'Gender' and whether respondents answered positively, neutrally or negatively to *Universal Exports does a good job of keeping me informed about important news and events*

In [13]:
df['Custom Column'] = df['Gender'] + "-" + df['Conditional Column']
df.head()

,Response id,Response Date,Department,Manager,Gender,Grade,Universal Exports does a good job of keeping me informed about important news and events,I get a sense of achievement from the work I do in my job,Universal Exports has created an environment that encourages me to perform to the best of my abilities,I am proud to work for Universal Exports,I trust and respect the management of Universal Exports,I believe that Universal Exports really cares about my health and wellbeing,"All in all, Universal Exports is effectively managed and well-run",I believe that Universal Exports has fair and transparent processes for promoting people into new roles,I have access to opportunities to develop my career in Universal Exports,My manager treats me fairly,Conditional Column,Custom Column
0,4,2020-07-13,IT,No,Female,A,5,4,4,5,4,3,4,4,2,4,Positive,Female-Positive
1,21,2020-07-13,Marketing,No,Male,C,4,4,3,4,4,5,3,3,4,5,Positive,Male-Positive
2,22,2020-07-13,Finance,No,Female,A,5,4,4,4,4,3,3,2,4,4,Positive,Female-Positive
3,25,2020-07-13,Finance,No,Male,B,3,5,4,4,4,4,4,3,3,5,Neutral,Male-Neutral
4,54,2020-07-13,Legal,No,Male,B,4,4,4,4,3,4,4,3,4,4,Positive,Male-Positive

**Unpivot all the question columns**

In [14]:
id_variables = list(df.columns[:6])
value_variables = list(df.columns[6:])

id_variables
df_melted =  pd.melt(df, id_vars = id_variables, value_vars = value_variables, var_name = "Question", value_name = "Answer")

In [15]:
df_melted

,Response id,Response Date,Department,Manager,Gender,Grade,Question,Answer
0,4,2020-07-13,IT,No,Female,A,Universal Exports does a good job of keeping m...,5
1,21,2020-07-13,Marketing,No,Male,C,Universal Exports does a good job of keeping m...,4
2,22,2020-07-13,Finance,No,Female,A,Universal Exports does a good job of keeping m...,5
3,25,2020-07-13,Finance,No,Male,B,Universal Exports does a good job of keeping m...,3
4,54,2020-07-13,Legal,No,Male,B,Universal Exports does a good job of keeping m...,4
...,...,...,...,...,...,...,...,...
11995,899,2020-07-24,Legal,Yes,Female,D,Custom Column,Female-Positive
11996,901,2020-07-24,Marketing,Yes,Female,D,Custom Column,Female-Negative
11997,908,2020-07-24,Finance,Yes,Female,D,Custom Column,Female-Neutral
11998,910,2020-07-24,IT,Yes,Male,D,Custom Column,Male-Positive
11999,969,2020-07-24,Legal,Yes,Female,D,Custom Column,Female-Positive

### Task 3 - Exporting Final Output and Analysis

In [16]:
output = df_melted.copy()

In [17]:
output.to_excel("Data_Modified.xlsx", index = False)